Update mongo-connector_2.5 to install [jq](https://stedolan.github.io/jq/)
To be able to write a better health check script

diff --git a/mongo-connector_2.5/Dockerfile b/mongo-connector_2.5/Dockerfile
--- a/mongo-connector_2.5/Dockerfile
+++ b/mongo-connector_2.5/Dockerfile
@@ -2,6 +2,12 @@ FROM python:3.4
 
 LABEL maintainer="Ahmed Magdy <ahmed.magdy@quadric.net>"
 
+# Install jq to write a better healthcheck command that the oplog.timestamp contains exactly "${MONGO_REPLICA_SET_NAME}" in the first item in the list
+## Using something similar to: if cat /oplog.timestamp | jq '.[0]' | grep "${MONGO_REPLICA_SET_NAME}" ; then echo 'found!!'; exit 0; else echo 'not found!!'; exit 1; fi
+RUN apt-get update && \
+    apt-get install -y jq && \
+    rm -rf /var/lib/apt/lists/*
+
 COPY ./requirements.txt /tmp/requirements.txt
 
 RUN pip install -r /tmp/requirements.txt
